apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: assignment
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: anshul1224/k8s-voting-frontend:v2
          imagePullPolicy: Always
          env:
            - name: REACT_APP_APIHOSTPORT
              value: http://k8s-assignme-api-40ca63e9dd-385caaf179178de3.elb.ap-south-1.amazonaws.com
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
